<?php

$_COS_LANG_MODULE['Delete file'] = 'Slet fil';
$_COS_LANG_MODULE['Delete'] = 'Slet';
$_COS_LANG_MODULE['Edit file'] = 'Rediger filen';
$_COS_LANG_MODULE['Add file'] = 'Tilføj fil';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['No file was specified'] = 'Ingen fil blev angivet';
$_COS_LANG_MODULE['Edit files'] = 'Redigere filer';
$_COS_LANG_MODULE['Download'] = 'Hent';
$_COS_LANG_MODULE['Edit'] = 'Rediger';
$_COS_LANG_MODULE['File was added'] = 'Fil blev tilsat';
$_COS_LANG_MODULE['File was deleted'] = 'Filen blev slettet';
$_COS_LANG_MODULE['File was edited'] = 'File blev redigeret';
