<?php

// Translation of file /home/dennis/www/osnet/modules/files/delete.php

$_COS_LANG_MODULE['files_edit_file'] = 'Ret fil';
// Translation of file /home/dennis/www/osnet/modules/files/add.php

$_COS_LANG_MODULE['files_add_file'] = 'Rediger filer';
// Translation of file /home/dennis/www/osnet/modules/files/model.files.inc

$_COS_LANG_MODULE['files_delete_file'] = 'Slet fil';

$_COS_LANG_MODULE['files_edit_label'] = 'Ret fil';
$_COS_LANG_MODULE['files_delete_label'] = 'Slet fil';
$_COS_LANG_MODULE['files_add_label'] = 'Tilføj fil';

$_COS_LANG_MODULE['files_edit'] = 'Ret';
$_COS_LANG_MODULE['files_delete'] = 'Slet';
$_COS_LANG_MODULE['files_add'] = 'Rediger filer';

$_COS_LANG_MODULE['files_form_abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['files_form_file'] = 'Vælg fil';
$_COS_LANG_MODULE['files_delete_caption'] = 'Slet fil';
$_COS_LANG_MODULE['files_edit_caption'] = 'Ret fil';
$_COS_LANG_MODULE['files_add_caption'] = 'Tilføj ny fil';
$_COS_LANG_MODULE['files_no_file_specified'] = 'Ingen fil valgt';
$_COS_LANG_MODULE['files_file_too_big'] = 'Fil er for stor';

$_COS_LANG_MODULE['files_attached'] = 'Filer';
$_COS_LANG_MODULE['files_download'] = 'Download';

$_COS_LANG_MODULE['files_add_new'] = 'Tilføj ny';
$_COS_LANG_MODULE['files_file_added'] = 'Fil tilføjet';
$_COS_LANG_MODULE['files_file_deleted'] = 'Fil slettet';
$_COS_LANG_MODULE['files_file_edited'] = 'Fil rettet';
// Translation of file /home/dennis/www/osnet/modules/files/edit.php


$_COS_LANG_MODULE['file_delete_label'] = 'Bekræft slet fil';
$_COS_LANG_MODULE['file_edit_legend'] = 'Ret Fil';
$_COS_LANG_MODULE['file_add_legend'] = 'Tilføj Fil';
$_COS_LANG_MODULE['file_abstract_label'] = 'Abstrakt';
$_COS_LANG_MODULE['file_file_label'] = 'Vælg en fil';
$_COS_LANG_MODULE['files_submit'] = 'Send';

$_COS_LANG_MODULE['system_submit_delete'] = 'system_submit_delete';
