<?php

$_COS_LANG_MODULE['Delete file'] = '删除文件';
$_COS_LANG_MODULE['Add file'] = '添加文件';
$_COS_LANG_MODULE['Delete'] = '删除';
$_COS_LANG_MODULE['Edit file'] = '编辑文件';
$_COS_LANG_MODULE['Abstract'] = '摘要';
$_COS_LANG_MODULE['No file was specified'] = '没有指定的文件';
$_COS_LANG_MODULE['Edit files'] = '编辑文件';
$_COS_LANG_MODULE['Download'] = '下载';
$_COS_LANG_MODULE['Edit'] = '编辑';
$_COS_LANG_MODULE['File was added'] = '文件已添加';
$_COS_LANG_MODULE['File was deleted'] = '文件已被删除';
$_COS_LANG_MODULE['File was edited'] = '文件被编辑';
