<?php

// Translation of file /home/dennis/www/osnet/modules/files/delete.php

$_COS_LANG_MODULE['files_edit_file'] = 'Edit File';
// Translation of file /home/dennis/www/osnet/modules/files/add.php

$_COS_LANG_MODULE['files_add_file'] = 'Add File';
// Translation of file /home/dennis/www/osnet/modules/files/model.files.inc

$_COS_LANG_MODULE['files_delete_file'] = 'Delete File';

$_COS_LANG_MODULE['files_edit_label'] = 'Edit File';
$_COS_LANG_MODULE['files_delete_label'] = 'Delete File';
$_COS_LANG_MODULE['files_add_label'] = 'Add File';

$_COS_LANG_MODULE['files_edit'] = 'Edit';
$_COS_LANG_MODULE['files_delete'] = 'Delete';
$_COS_LANG_MODULE['files_add'] = 'Edit files';

$_COS_LANG_MODULE['files_form_abstract'] = 'Abstract';
$_COS_LANG_MODULE['files_form_file'] = 'Select File';
$_COS_LANG_MODULE['files_delete_caption'] = 'Delete File';
$_COS_LANG_MODULE['files_edit_caption'] = 'Edit File';
$_COS_LANG_MODULE['files_add_caption'] = 'Add new file';
$_COS_LANG_MODULE['files_no_file_specified'] = 'No file specified';
$_COS_LANG_MODULE['files_file_too_big'] = 'file is to big';

$_COS_LANG_MODULE['files_attached'] = 'Files';
$_COS_LANG_MODULE['files_download'] = 'Download';

$_COS_LANG_MODULE['files_add_new'] = 'Add New';
$_COS_LANG_MODULE['files_file_added'] = 'File Added';
$_COS_LANG_MODULE['files_file_deleted'] = 'File Deleted';
$_COS_LANG_MODULE['files_file_edited'] = 'File Edited';
// Translation of file /home/dennis/www/osnet/modules/files/edit.php


$_COS_LANG_MODULE['file_delete_label'] = 'Delete File';
$_COS_LANG_MODULE['system_submit_delete'] = 'Delete';
$_COS_LANG_MODULE['file_edit_legend'] = 'Edit File';
$_COS_LANG_MODULE['file_add_legend'] = 'Add File';
$_COS_LANG_MODULE['file_abstract_label'] = 'Abstract';
$_COS_LANG_MODULE['file_file_label'] = 'File';
