<?php


// Translation of file /modules/files/delete.php

$_COS_LANG_MODULE['Delete file'] = 'Delete file';
$_COS_LANG_MODULE['Add file'] = 'Add file';

// Translation of file /modules/files/model.files.inc

$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Edit file'] = 'Edit file';
$_COS_LANG_MODULE['Abstract'] = 'Abstract';
$_COS_LANG_MODULE['No file was specified'] = 'No file was specified';
$_COS_LANG_MODULE['Edit files'] = 'Edit files';
$_COS_LANG_MODULE['Download'] = 'Download';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['File was added'] = 'File was added';
$_COS_LANG_MODULE['File was deleted'] = 'File was deleted';
$_COS_LANG_MODULE['File was edited'] = 'File was edited';

// Translation of file /modules/files/add.php


// Translation of file /modules/files/edit.php
