<?php

$_COS_LANG_MODULE['Edit file'] = 'Rediger filen';
$_COS_LANG_MODULE['Add file'] = 'Legg til fil';
$_COS_LANG_MODULE['Delete file'] = 'Slett fil';
$_COS_LANG_MODULE['Edit'] = 'Rediger';
$_COS_LANG_MODULE['Delete'] = 'Slett';
$_COS_LANG_MODULE['Add new file'] = 'Legg til ny fil';
$_COS_LANG_MODULE['No file was specified'] = 'Ingen fil ble spesifisert';
$_COS_LANG_MODULE['Download'] = 'Last ned';
$_COS_LANG_MODULE['File was added'] = 'Filen ble lagt';
$_COS_LANG_MODULE['File was deleted'] = 'Filen ble slettet';
$_COS_LANG_MODULE['File was edited'] = 'Filen var redigert';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['File'] = 'Fil';
$_COS_LANG_MODULE['Edit files'] = 'Redigere filer';
