<?php

$_COS_LANG_MODULE['Delete file'] = 'Datei löschen';
$_COS_LANG_MODULE['Delete'] = 'Löschen';
$_COS_LANG_MODULE['Edit file'] = 'Datei bearbeiten';
$_COS_LANG_MODULE['Add file'] = 'Datei hinzufügen';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['No file was specified'] = 'Keine Datei angegeben wurde';
$_COS_LANG_MODULE['Edit files'] = 'Bearbeiten von Dateien';
$_COS_LANG_MODULE['Download'] = 'Herunterladen';
$_COS_LANG_MODULE['Edit'] = 'Bearbeiten';
$_COS_LANG_MODULE['File was added'] = 'Die Datei wurde hinzugefügt';
$_COS_LANG_MODULE['File was deleted'] = 'Datei gelöscht wurde';
$_COS_LANG_MODULE['File was edited'] = 'Datei bearbeitet wurde';
