<?php

$_COS_LANG_MODULE['Delete file'] = 'Poista tiedosto';
$_COS_LANG_MODULE['Add file'] = 'Lisää tiedosto';
$_COS_LANG_MODULE['Edit file'] = 'Muokkaa tiedosto';
$_COS_LANG_MODULE['Delete'] = 'Poistaa';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakti';
$_COS_LANG_MODULE['No file was specified'] = 'Tiedostoa ei määritelty';
$_COS_LANG_MODULE['Edit files'] = 'Muokata tiedostoja';
$_COS_LANG_MODULE['Download'] = 'Lataa';
$_COS_LANG_MODULE['Edit'] = 'Muokata';
$_COS_LANG_MODULE['File was added'] = 'Tiedosto on lisätty';
$_COS_LANG_MODULE['File was deleted'] = 'Tiedosto poistettiin';
$_COS_LANG_MODULE['File was edited'] = 'Tiedosto oli muokattu';
