<?php

$_COS_LANG_MODULE['Edit file'] = 'Edit file';
$_COS_LANG_MODULE['Add file'] = 'Add file';
$_COS_LANG_MODULE['Delete file'] = 'Delete file';
$_COS_LANG_MODULE['Edit'] = 'Edit';
$_COS_LANG_MODULE['Delete'] = 'Delete';
$_COS_LANG_MODULE['Add new file'] = 'Add new file';
$_COS_LANG_MODULE['No file was specified'] = 'No file was specified';
$_COS_LANG_MODULE['Download'] = 'Download';
$_COS_LANG_MODULE['File was added'] = 'File was added';
$_COS_LANG_MODULE['File was deleted'] = 'File was deleted';
$_COS_LANG_MODULE['File was edited'] = 'File was edited';
$_COS_LANG_MODULE['Abstract'] = 'Abstract';
$_COS_LANG_MODULE['File'] = 'File';
$_COS_LANG_MODULE['Edit files'] = 'Redigera filer';
