<?php

$_COS_LANG_MODULE['Edit file'] = 'Redigera filen';
$_COS_LANG_MODULE['Add file'] = 'Lägg filen';
$_COS_LANG_MODULE['Delete file'] = 'Radera fil';
$_COS_LANG_MODULE['Edit'] = 'Redigera';
$_COS_LANG_MODULE['Delete'] = 'Radera';
$_COS_LANG_MODULE['Add new file'] = 'Lägg till ny fil';
$_COS_LANG_MODULE['No file was specified'] = 'Ingen fil angavs';
$_COS_LANG_MODULE['Download'] = 'Ladda ner';
$_COS_LANG_MODULE['File was added'] = 'Arkiv sattes';
$_COS_LANG_MODULE['File was deleted'] = 'Filen raderades';
$_COS_LANG_MODULE['File was edited'] = 'Arkiv redigerades';
$_COS_LANG_MODULE['Abstract'] = 'Abstrakt';
$_COS_LANG_MODULE['File'] = 'Fil';
$_COS_LANG_MODULE['Edit files'] = 'Redigera filer';
